AllCops:
  Exclude:
  - 'db/**/*'
  - 'bin/*'

Metrics/LineLength:
  Max: 80

Style/BlockComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false
